# Generated by Django 5.2.10 on 2026-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
