# Generated by Django 5.2.10 on 2026-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionitem_id_alter_bid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='end_date',
            field=models.DateTimeField(default='2026-12-31 23:59:59'),
            preserve_default=False,
        ),
    ]
