# Generated by Django 5.2.10 on 2026-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('vehicles', 'Vehicles'), ('toys', 'Toys & Collectibles'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
