# Generated by Django 5.2.10 on 2026-02-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
